[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "dx-toolkit"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
pandas = "==1.3.5"
pyspark = ">=3.5.5,<4"

[pypi-dependencies]
dxpy = ">=0.394.0, <0.395"
jupyterlab = ">=4.4.0, <5"


